// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWg6Qt6Ii1w8EcOJsjOid6_eTZS55UTUk',
    appId: '1:792118650082:web:f481cc149ef17ddbd66abb',
    messagingSenderId: '792118650082',
    projectId: 'elmoktaser',
    authDomain: 'elmoktaser.firebaseapp.com',
    storageBucket: 'elmoktaser.appspot.com',
    measurementId: 'G-6GJGVQTM22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWxn3TTS3dhSnnyUGRtuWB79CrIMJqdOU',
    appId: '1:792118650082:android:9acac281b89ecb8fd66abb',
    messagingSenderId: '792118650082',
    projectId: 'elmoktaser',
    storageBucket: 'elmoktaser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzrRZs0A65bYextVefhAYxQfWUW_G-GA',
    appId: '1:792118650082:ios:4316296b22bd2194d66abb',
    messagingSenderId: '792118650082',
    projectId: 'elmoktaser',
    storageBucket: 'elmoktaser.appspot.com',
    iosClientId: '792118650082-aq6qhping9pg2nacg0m58iushvliqmvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.elmoktaserElshamel',
  );
}
